version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - '3333:3333'
    env_file: .env.development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src

  postgres:
    container_name: clock-in-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: clock-in
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

